### ISSUE TITLE
うごいてない

### ISSUE THREAD

**Issue by tamaina** [syuilo/misskey-github-notifier#2]
サーバー代を払ってないとかで動いてないのですが、割と不便……  
@cookieramen に頼んで再開してほしいです。

**Comment by syuilo** [comment]
一応頼んではあります

**Comment by CookieRamen** [comment]
わざわざIssue立てなくても
リプライ送るだけじゃ駄目なんですか？
正直うるさいです。

**Comment by tamaina** [comment]
あっはいすみません
